# **Pandas Library**

Pandas is the most popular open-source Python library used for data manipulation, analysis, and cleaning. Built directly on top of NumPy, it provides fast and flexible tools to work with structured, tabular data like spreadsheets or SQL tables.

In [75]:
import pandas as pd

Pandas Series and Pandas DataFrames are the two primary data structures used in Python's Pandas library for data cleaning, manipulation, and analysis. The core difference is that a Series represents a single column (1D array), while a DataFrame represents an entire table (2D array) made up of multiple columns.

## **Quick Comparison: Series vs. DataFrame**

When working with Pandas, it's crucial to understand the difference between its two core data structures. 

| Feature | `Pandas Series` | `Pandas DataFrame` |
| :--- | :--- | :--- |
| **Dimensions** | 1D (Single column) | 2D (Rows & Columns) |
| **Data Types** | Homogeneous (Usually one type per Series) | Heterogeneous (Different types per column) |
| **Analogy** | A single column in Excel | An entire Excel spreadsheet |
| **Creation** | Lists, dictionaries, or 1D arrays | Dictionary of arrays, lists of dicts, or CSVs |

## **Pandas Series**

A **Series** is the fundamental building block of Pandas. It is a one-dimensional array capable of holding any data type. Notice how Pandas automatically generates a numeric index (0, 1, 2...) next to your data!

In [3]:
temparatures = pd.Series([32, 45, 28, 30, 35])
print(temparatures)
print(type(temparatures))

0    32
1    45
2    28
3    30
4    35
dtype: int64
<class 'pandas.Series'>

In [5]:
temparatures = pd.Series([32, 45, 28, 30, 35], index=["Monday","Tuesday","Wednesday","Thrusday","Friday"])
print(temparatures)

Monday       32
Tuesday      45
Wednesday    28
Thrusday     30
Friday       35
dtype: int64

## **`.loc` and `.iloc`**

- The primary difference between .loc and .iloc in a Pandas DataFrame is that .loc uses label-based indexing to select data by names, while .iloc uses integer-based indexing to select data by numerical positions. Both attributes use the identical syntax format of df.method[row_indexer, column_indexer] to look up or slice your data.

- When slicing and selecting data in a Pandas DataFrame, understanding the difference between label-based and position-based indexing will save you from constant errors. 

| Feature | `.loc` | `.iloc` |
| :--- | :--- | :--- |
| **Indexing Basis** | Custom Row/Column labels (names). | Integer positions (0-indexed). |
| **Slicing Endpoint** | **Inclusive** (both start and stop labels appear). | **Exclusive** (stops right before the end index). |
| **Boolean Filtering** | Supported natively (e.g., `df['Age'] > 30`). | Not supported directly with boolean Series. |
| **Missing Keys** | Raises a `KeyError`. | Raises an `IndexError` if out-of-bounds. |

In [10]:
temparatures = pd.Series([32, 45, 28, 30, 35], index=["Monday","Tuesday","Wednesday","Thrusday","Friday"])
print(temparatures.iloc[4])
print(temparatures.loc["Friday"])

35
35

In [12]:
data = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [20, 25, 30],
    "Gender" : ["F", "M", "M"]
}

dt = pd.DataFrame(data)
print(dt)
print(type(dt))

      Name  Age Gender
0    Alice   20      F
1      Bob   25      M
2  Charlie   30      M
<class 'pandas.DataFrame'>

## **Pandas DataFrame**

A Pandas DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It is the primary data structure used in the Python Pandas library, functioning much like an Excel spreadsheet or a SQL table.

- Key Characteristics
    - **Two-Dimensional**: Data is organized cleanly into rows and columns.
    - **Heterogeneous**: Different columns can hold completely different data types (e.g., strings, integers, dates).
    - **Labeled Axes**: Rows have an index and columns have names for direct, semantic referencing.

In [15]:
data = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [20, 25, 30],
    "Gender" : ["F", "M", "M"]
}

dt = pd.DataFrame(data, index=["Student_1", "Student_2", "Student_3"])
print(dt)
print(type(dt))

              Name  Age Gender
Student_1    Alice   20      F
Student_2      Bob   25      M
Student_3  Charlie   30      M
<class 'pandas.DataFrame'>

In [52]:
data = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [20, 25, 30],
    "Gender" : ["F", "M", "M"]
}

dt = pd.DataFrame(data, index=["Student_1", "Student_2", "Student_3"])

# Accessing data using iloc and loc
print(f"iloc in 30 : {dt.iloc[2, 1]}")
print(f"loc in 30: {dt.loc["Student_3","Age"]}\n")

# Accessing data in Rows
print(f"Student_2 row : \n{dt.iloc[1]}")
print(f"type of Student_2 row : {type(dt.iloc[1])}\n")

# Accessing data in Colomns
print(f"Age Colomn : \n{dt["Age"]}")
print(f"type of Age Colomn : {type(dt["Age"])}\n")

print(f"Shape of dt : {dt.shape}")
print(f"Size of dt : {dt.size}\n")
print(f"len of dt(Number of Rows) :  {len(dt)}\n")  #Number of Rows
print(f"dTypes of dt : \n{dt.dtypes}\n")

iloc in 30 : 30
loc in 30: 30

Student_2 row :
Name      Bob
Age        25
Gender      M
Name: Student_2, dtype: object
type of Student_2 row : <class 'pandas.Series'>

Age Colomn :
Student_1    20
Student_2    25
Student_3    30
Name: Age, dtype: int64
type of Age Colomn : <class 'pandas.Series'>

Shape of dt : (3, 3)
Size of dt : 9

len of dt(Number of Rows) :  3

dTypes of dt :
Name        str
Age       int64
Gender      str
dtype: object

In [60]:
data = {
    "Name" : ["Alice", "Bob", "Charlie"],
    "Age" : [20, 25, 30],
    "Gender" : ["F", "M", "M"]
}

dt = pd.DataFrame(data, index=["Student_1", "Student_2", "Student_3"])

colomn_names = dt.columns
print(colomn_names)
print(type(colomn_names))

print(list(colomn_names))

values = dt.values
print(values)
print(type(values))

Index(['Name', 'Age', 'Gender'], dtype='str')
<class 'pandas.Index'>
['Name', 'Age', 'Gender']
[['Alice' 20 'F']
 ['Bob' 25 'M']
 ['Charlie' 30 'M']]
<class 'numpy.ndarray'>

In [61]:
data = {
    "Age" : [10,20,30,40],
    "Salary" : [10000,20000,30000,40000]
}

df = pd.DataFrame(data)
df

   Age  Salary
0   10   10000
1   20   20000
2   30   30000
3   40   40000

## **1. The `.sum()` Method**
* **What it does:** Calculates the total sum of the values.
* **How it works:** When applied to a DataFrame, it calculates the sum for *each column* individually. If applied to a single Series (one column), it returns a single total number.
* **Common Use Case:** Finding total annual sales, calculating total inventory volume, or summing up user activity points.

In [ ]:
data = {
    "Age" : [10,20,30,40],
    "Salary" : [10000,20000,30000,40000]
}

df = pd.DataFrame(data)
print(f"Sum : \n{df.sum()}")  #Sum of Each numaric values
# df.sum()

Sum :
Age          100
Salary    100000
dtype: int64

## **2. The `.mean()` Method**
* **What it does:** Calculates the arithmetic average of the values.
* **How it works:** Just like `.sum()`, it automatically scans your numeric columns and returns the average for each one. Missing data (`NaN`) is automatically ignored by default.
* **Common Use Case:** Finding the average age of your user base, calculating average monthly revenue, or finding typical test scores.

In [ ]:
data = {
    "Age" : [10,20,30,40],
    "Salary" : [10000,20000,30000,40000]
}

df = pd.DataFrame(data)  
print(f"Mean : \n{df.mean()}")
# df.mean()

Age          25.0
Salary    25000.0
dtype: float64

## **3. The `.describe()` Method (The Ultimate Summary)**
* **What it does:** Generates a comprehensive, high-level statistical summary table of all numeric columns in your DataFrame.
* **What it includes:** In one single command, it returns:
  * **`count`**: Number of non-empty rows (great for spotting missing data).
  * **`mean`**: The average.
  * **`std`**: Standard deviation (how spread out or volatile the data is). (සම්මත අපගමනය)
  * **`min` & `max`**: The absolute lowest and highest values.
  * **`25%, 50%, 75%`**: The percentiles (note: the `50%` is your median). (චතුර්තක -> Q1,Q2,Q2)
* **When to use it:** This should almost always be the very first command you run when you load a brand new dataset to check for extreme outliers and understand your data's distribution.

In [80]:
data = {
    "Age" : [10,20,30,40],
    "Salary" : [10000,20000,30000,40000]
}

df = pd.DataFrame(data)
# print(f"Describe : \n{df.describe()}")
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   25.000000  25000.000000
std    12.909944  12909.944487
min    10.000000  10000.000000
25%    17.500000  17500.000000
50%    25.000000  25000.000000
75%    32.500000  32500.000000
max    40.000000  40000.000000

In [82]:
data = {
    "Age" : [10,20,30,40],
    "Salary" : [10000,20000,30000,40000]
}
df = pd.DataFrame(data)

filterd_df = df[df["Age"] > 25]
filterd_df

   Age  Salary
2   30   30000
3   40   40000

In [127]:
data = {
    "Age" : [35,20,22,40],
    "Salary" : [10000,20000,30000,40000]
}
df = pd.DataFrame(data)
filtered_df = df[(df["Age"] > 25) & (df["Salary"] < 300000)]
filterd_df

   Age  Salary
2   30   30000
3   40   40000

In [ ]:
data = {
    "Age" : [35,20,22,40],
    "Salary" : [10000,20000,90000,40000]
}
df = pd.DataFrame(data)

sorted_df_age = df.sort_values(by="Age")
sorted_df_age

   Age  Salary
1   20   20000
2   22   90000
0   35   10000
3   40   40000

In [133]:
sorted_df_salary = df.sort_values(by="Salary")
sorted_df_salary

   Age  Salary
0   35   10000
1   20   20000
3   40   40000
2   22   90000

## **Add a Row and Column**

In [155]:
# Add a new Column Distance -> 8,4,20,17

data = {
    "Age" : [35,20,22,40],
    "Salary" : [50000,60000,70000,80000]
}

df = pd.DataFrame(data)

df["Distance"] = [8,4,20,17]
df

   Age  Salary  Distance
0   35   50000         8
1   20   60000         4
2   22   70000        20
3   40   80000        17

In [156]:
# Add a new Row -> 38, 780000, 15

df.loc[4] = [38, 780000, 15]
df

   Age  Salary  Distance
0   35   50000         8
1   20   60000         4
2   22   70000        20
3   40   80000        17
4   38  780000        15

## **Drop a Row or Column**

- The code `DataFrame.drop(labels, axis=1, inplace=False)` is used in the Python pandas library to remove one or more columns from a dataset. It generates a brand-new dataset without the chosen columns, leaving your original data completely unchanged.

    - labels: The name (or list of names) of the column(s) you want to remove.
        - Example: `"Age"` to drop one column, or `["Age", "Salary"]` to drop multiple columns.

    - axis=1: Tells pandas to look for the labels horizontally across the columns.By default, pandas looks at `axis=0` **(rows)**. Setting `axis=1` **(or axis='columns')** is required to avoid a "label not found" error when deleting columns.

    - inplace=False: Ensures the method returns a new DataFrame with the specified columns removed.Because it defaults to False, your original DataFrame remains intact. If you want to modify your original dataset directly without assigning it to a new variable, you would change this to inplace=True

In [159]:
data = {
    "Age" : [35,20,22,40],
    "Salary" : [50000,60000,70000,80000],
    "Distance" : [10,20,30,10]
}

df = pd.DataFrame(data)

drop_column = df.drop("Distance", axis=1)
drop_column

   Age  Salary
0   35   50000
1   20   60000
2   22   70000
3   40   80000

# **csv format converts to pandas**
- To convert a CSV file into a Pandas DataFrame format, use the `pd.read_csv()` function.

In [160]:
df = pd.read_csv("sample (1).csv")
print(df)

    id           name  age           city  salary
0    1  Alice Johnson   28       New York   55000
1    2      Bob Smith   34    Los Angeles   62000
2    3  Charlie Brown   45        Chicago   78000
3    4   Diana Prince   29        Houston   59000
4    5     Ethan Hunt   38        Phoenix   71000
5    6    Fiona Apple   26   Philadelphia   52000
6    7  George Miller   52    San Antonio   85000
7    8     Hannah Lee   31      San Diego   64000
8    9     Ian Wright   40         Dallas   73000
9   10  Julia Roberts   35       San Jose   68000
10  11     Kevin Hart   33         Austin   66000
11  12   Laura Palmer   27   Jacksonville   54000
12  13  Michael Scott   48     Fort Worth   82000
13  14    Nina Simone   30       Columbus   61000
14  15    Oscar Wilde   42      Charlotte   75000
15  16    Paula Abdul   36  San Francisco   69000
16  17   Quincy Jones   55   Indianapolis   90000
17  18   Rachel Green   32        Seattle   67000
18  19   Steve Rogers   41         Denver   74000
19  20    Tina Turner   39     Washington   72000

In [161]:
print(df.head())

   id           name  age         city  salary
0   1  Alice Johnson   28     New York   55000
1   2      Bob Smith   34  Los Angeles   62000
2   3  Charlie Brown   45      Chicago   78000
3   4   Diana Prince   29      Houston   59000
4   5     Ethan Hunt   38      Phoenix   71000